/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetingCreateRouteImport } from './routes/meeting/create'
import { Route as MeetingJoinIndexRouteImport } from './routes/meeting/join/index'
import { Route as MeetingMeetingIdIndexRouteImport } from './routes/meeting/$meetingId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingCreateRoute = MeetingCreateRouteImport.update({
  id: '/meeting/create',
  path: '/meeting/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingJoinIndexRoute = MeetingJoinIndexRouteImport.update({
  id: '/meeting/join/',
  path: '/meeting/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingMeetingIdIndexRoute = MeetingMeetingIdIndexRouteImport.update({
  id: '/meeting/$meetingId/',
  path: '/meeting/$meetingId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meeting/create': typeof MeetingCreateRoute
  '/meeting/$meetingId': typeof MeetingMeetingIdIndexRoute
  '/meeting/join': typeof MeetingJoinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meeting/create': typeof MeetingCreateRoute
  '/meeting/$meetingId': typeof MeetingMeetingIdIndexRoute
  '/meeting/join': typeof MeetingJoinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meeting/create': typeof MeetingCreateRoute
  '/meeting/$meetingId/': typeof MeetingMeetingIdIndexRoute
  '/meeting/join/': typeof MeetingJoinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meeting/create' | '/meeting/$meetingId' | '/meeting/join'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meeting/create' | '/meeting/$meetingId' | '/meeting/join'
  id:
    | '__root__'
    | '/'
    | '/meeting/create'
    | '/meeting/$meetingId/'
    | '/meeting/join/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeetingCreateRoute: typeof MeetingCreateRoute
  MeetingMeetingIdIndexRoute: typeof MeetingMeetingIdIndexRoute
  MeetingJoinIndexRoute: typeof MeetingJoinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/create': {
      id: '/meeting/create'
      path: '/meeting/create'
      fullPath: '/meeting/create'
      preLoaderRoute: typeof MeetingCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/join/': {
      id: '/meeting/join/'
      path: '/meeting/join'
      fullPath: '/meeting/join'
      preLoaderRoute: typeof MeetingJoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/$meetingId/': {
      id: '/meeting/$meetingId/'
      path: '/meeting/$meetingId'
      fullPath: '/meeting/$meetingId'
      preLoaderRoute: typeof MeetingMeetingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeetingCreateRoute: MeetingCreateRoute,
  MeetingMeetingIdIndexRoute: MeetingMeetingIdIndexRoute,
  MeetingJoinIndexRoute: MeetingJoinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
