/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AppCalendarIndexRouteImport } from './routes/_app/calendar/index'
import { Route as AppMeetingCreateRouteImport } from './routes/_app/meeting/create'
import { Route as AppMeetingJoinIndexRouteImport } from './routes/_app/meeting/join/index'
import { Route as AppMeetingMeetingIdIndexRouteImport } from './routes/_app/meeting/$meetingId/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingCreateRoute = AppMeetingCreateRouteImport.update({
  id: '/meeting/create',
  path: '/meeting/create',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingJoinIndexRoute = AppMeetingJoinIndexRouteImport.update({
  id: '/meeting/join/',
  path: '/meeting/join/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingMeetingIdIndexRoute =
  AppMeetingMeetingIdIndexRouteImport.update({
    id: '/meeting/$meetingId/',
    path: '/meeting/$meetingId/',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/meeting/create': typeof AppMeetingCreateRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/meeting/$meetingId': typeof AppMeetingMeetingIdIndexRoute
  '/meeting/join': typeof AppMeetingJoinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/meeting/create': typeof AppMeetingCreateRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/meeting/$meetingId': typeof AppMeetingMeetingIdIndexRoute
  '/meeting/join': typeof AppMeetingJoinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/meeting/create': typeof AppMeetingCreateRoute
  '/_app/calendar/': typeof AppCalendarIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_app/meeting/$meetingId/': typeof AppMeetingMeetingIdIndexRoute
  '/_app/meeting/join/': typeof AppMeetingJoinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/meeting/create'
    | '/calendar'
    | '/login'
    | '/meeting/$meetingId'
    | '/meeting/join'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meeting/create'
    | '/calendar'
    | '/login'
    | '/meeting/$meetingId'
    | '/meeting/join'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/'
    | '/_app/meeting/create'
    | '/_app/calendar/'
    | '/_auth/login/'
    | '/_app/meeting/$meetingId/'
    | '/_app/meeting/join/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/calendar/': {
      id: '/_app/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meeting/create': {
      id: '/_app/meeting/create'
      path: '/meeting/create'
      fullPath: '/meeting/create'
      preLoaderRoute: typeof AppMeetingCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meeting/join/': {
      id: '/_app/meeting/join/'
      path: '/meeting/join'
      fullPath: '/meeting/join'
      preLoaderRoute: typeof AppMeetingJoinIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meeting/$meetingId/': {
      id: '/_app/meeting/$meetingId/'
      path: '/meeting/$meetingId'
      fullPath: '/meeting/$meetingId'
      preLoaderRoute: typeof AppMeetingMeetingIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppMeetingCreateRoute: typeof AppMeetingCreateRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppMeetingMeetingIdIndexRoute: typeof AppMeetingMeetingIdIndexRoute
  AppMeetingJoinIndexRoute: typeof AppMeetingJoinIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppMeetingCreateRoute: AppMeetingCreateRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppMeetingMeetingIdIndexRoute: AppMeetingMeetingIdIndexRoute,
  AppMeetingJoinIndexRoute: AppMeetingJoinIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
